version: '3'
services:
  db:
    image: mysql:5.7
    restart: always
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --init-connect='SET NAMES utf8mb4;' --innodb-flush-log-at-trx-commit=0
    ports:
      - 3306:3306
    volumes:
      - ./dockermysql:/var/lib/mysql:rw
    environment:
      - MYSQL_DATABASE=automationdb
      - MYSQL_ROOT_PASSWORD=123456